#' Create RCT Survival Metadata
#'
#' Create RCT survival metadata to be used for estimation of the
#' restricted mean survival time and survival probability.
#'
#' @param outcome.formula An object of class "formula". The left hand side should be
#'   specified using \code{Surv(time, status)} where time is the name of the
#'   variable containing follow-up time and status is the name of the indicator variable
#'   with 0 = right censored and 1 = event at \code{time}. The right hand
#'   side should contain the target variable of interest and baseline prognostic covariates.
#' @param trt.formula An object of class "formula". The left hand side should be the name
#'   of the binary (coded as 0 and 1) treatment variable. The right hand side should specify the
#'   names of variables used to estimate the propensity.
#' @param data A data frame containing the variables in the model.
#' @param coarsen An optional integer that specifies if and how \code{time} should
#'   be categorized into coarser intervals.
#' @param estimator The method to be used for computing estimands. Options are \code{"tmle"}
#'   for Targeted Maximum Likelihood Estimation (the default) and \code{"aipw"} for Augmented IPW.
#' @param algo Method to be used for fitting the hazard and censoring nuisance parameters.
#'   Automatically set to \code{"glm"} if less than two covariates for adjustment are
#'   specified in \code{outcome.formula}. The propensity is always estimated using a GLM.
#' @crossfit Should the estimator be crossfit? Ignored if \code{algo} is \code{"glm"} or \code{"lasso"}.
#'
#' @family survrct functions
#'
#' @return An R6 object of class "Survival".
#' @export
#'
#' @examples
#' \donttest{
#' survrct(Surv(days, event) ~ trt + age + sex + dyspnea + bmi,
#'         trt ~ 1, data = c19.tte, estimator = "tmle", algo = "lasso")
#' }
survrct <- function(outcome.formula, trt.formula,
                    data, coarsen = 1,
                    estimator = c("tmle", "aipw"),
                    algo = c("glm", "lasso", "rf", "xgboost"),
                    crossfit = TRUE) {
  Survival$
    new(outcome.formula, trt.formula, data, match.arg(estimator))$
    prepare_data(coarsen)$
    fit_nuis(match.arg(algo), crossfit)
}

#' Estimate Restricted Mean Survival Time
#'
#' @param metadata An object of class "Survival" generated by a call to \code{survrct()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   RMST at all possible time horizons.
#'
#' @family survrct functions
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{rmst} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{horizon}{The time horizons RMST was evaluated at.}
#' \item{estimates}{The computed estimates for each time horizon including
#'                       the efficient influence function, standard errors, and
#'                       confidence intervals.}
#'
#' @export
#'
#' @examples
#' \donttest{
#' surv <- survrct(Surv(days, event) ~ trt + age + sex + dyspnea + bmi,
#'                 trt ~ 1, data = c19.tte, estimator = "tmle", algo = "lasso")
#' rmst(surv, 14)
#' }
rmst <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "rmst")
  out <- list(estimator = metadata$estimator,
              horizon = metadata$horizon,
              estimates = compute_rmst(metadata))
  class(out) <- "rmst"
  out
}

#' Estimate Survival Probabilities
#'
#' @param metadata An object of class "Survival" generated by a call to \code{survrct()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   survival probabilities at all time points.
#'
#' @family survrct functions
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{survprob} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{horizon}{The time horizons the survival probability was evaluated at.}
#' \item{estimates}{The computed estimates for each time horizon including the
#'                       efficient influence function, standard errors,
#'                       and confidence intervals.}
#'
#' @export
#'
#' @examples
#' \donttest{
#' surv <- survrct(Surv(days, event) ~ trt + age + sex + dyspnea + bmi,
#'                 trt ~ 1, data = c19.tte, estimator = "tmle", algo = "lasso")
#' survprob(surv, 14)
#' }
survprob <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "survprob")
  out <- list(estimator = metadata$estimator,
              horizon = metadata$horizon,
              estimates = compute_survprob(metadata))
  class(out) <- "survprob"
  out
}

#' Create RCT Ordinal Metadata
#'
#' Create RCT ordinal metadata to be used for estimation of the
#' average log odds ratio, counterfactual marginal CDFs, and Mann-Whitney statistic.
#'
#' @param formula An object of class "formula". The left hand side should be
#'   the outcome variable. The right hand
#'   side should contain the target variable of interest and baseline prognostic covariates.
#' @param target The name of the target variable of interest; i.e., the randomized condition.
#' @param data A data frame containing the variables in the model.
#' @param estimator The method to be used for computing estimands. Options are "tmle"
#'   for Targeted Maximum Likelihood Estimation (the default), "aipw" for Augmented IPW,
#'   and "unadjusted" for the unadjusted estimator.
#' @param algo Method to be used for fitting nuisance parameters. Automatically set to "glm" if
#'   less than two covariates for adjustment are specified in \code{formula}.
#'
#' @family ordinal functions
#'
#' @return An R6 object of class "Ordinal".
#' @export
ordinalrct <- function(outcome.formula,
                       trt.formula, data,
                       estimator = c("tmle", "aipw"),
                       algo = c("glm", "lasso", "rf", "xgboost"),
                       crossfit = TRUE) {
  Ordinal$
    new(outcome.formula, trt.formula, data, match.arg(estimator))$
    prepare_data()$
    fit_nuis(match.arg(algo), crossfit)
}

#' Estimate Average Log Odds Ratio
#'
#' @param metadata An object of class "Ordinal" generated by a call to \code{ordinalrct()}.
#'
#' @family ordinalrct functions
#' @seealso \code{\link{ordinalrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{lor} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{estimates}{The computed estimates including the
#'                       efficient influence function, standard errors,
#'                       and confidence intervals.}
#'
#' @export
log_or <- function(metadata) {
  out <- list(estimator = metadata$estimator,
              estimates = compute_lor(metadata))
  class(out) <- "lor"
  out
}

#' Estimate the Cumulative Distribution Function
#'
#' @param metadata An object of class "Ordinal" generated by a call to \code{ordinalrct()}.
#'
#' @family ordinalrct functions
#' @seealso \code{\link{ordinalrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{cdf} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{estimates}{The computed estimates including the
#'                       efficient influence function, standard errors,
#'                       and confidence intervals.}
#'
#' @export
cdf <- function(metadata) {
  out <- list(levels = levels(metadata$data[[metadata$Y]]),
              estimator = metadata$estimator,
              estimates = compute_cdf(metadata))
  class(out) <- "cdf"
  out
}

#' Estimate the Probability Mass Function
#'
#' @param metadata An object of class "Ordinal" generated by a call to \code{ordinalrct()}.
#'
#' @family ordinalrct functions
#' @seealso \code{\link{ordinalrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{pmf} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{estimates}{The computed estimates including the
#'                       efficient influence function, standard errors,
#'                       and confidence intervals.}
#'
#' @export
pmf <- function(metadata) {
  out <- list(levels = levels(metadata$data[[metadata$Y]]),
              estimator = metadata$estimator,
              estimates = compute_pmf(metadata))
  class(out) <- "pmf"
  out
}

#' Estimate the Mann-Whitney Estimand
#'
#' @param metadata An object of class "Ordinal" generated by a call to \code{ordinalrct()}.
#'
#' @family ordinalrct functions
#' @seealso \code{\link{ordinalrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{mannwhit} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{estimates}{The computed estimates including the
#'                       efficient influence function, standard errors,
#'                       and confidence intervals.}
#'
#' @export
mannwhitney <- function(metadata) {
  out <- list(estimator = metadata$estimator,
              estimates = compute_mw(metadata))
  class(out) <- "mannwhit"
  out
}

