
#' Create RCT Survival Metadata
#'
#' @param formula
#' @param target
#' @param data
#' @param coarsen
#' @param estimator
#' @param lrnrs_trt
#' @param lrnrs_cens
#' @param lrnrs_hzrd
#'
#' @return
#' @export
#'
#' @examples
survrct <- function(formula, target, data, coarsen, estimator,
                    lrnrs_trt = NULL, lrnrs_cens = NULL, lrnrs_hzrd = NULL) {
  Survival$
    new(formula, target, data, estimator, lrnrs_trt, lrnrs_cens, lrnrs_hzrd)$
    prepare_data(coarsen)$
    fit_nuis()
}

#' Estimate Restricted Mean Survival Time
#'
#' @param metadata A rctSurv Survival metadata object generated by a call to \code{metadata()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   RMST at all possible time horizons.
#'
#' @return
#' @export
#'
#' @examples
rmst <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "rmst")
  out <- list(estimator = metadata$estimator,
              horizon   = metadata$horizon,
              estimates = compute_rmst(metadata))
  class(out) <- "rmst"
  out
}

#' Estimate Survival Probabilities
#'
#' @param metadata A rctSurv Survival metadata object generated by a call to \code{metadata()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   survival probabilities at all time points.
#'
#' @return
#' @export
#'
#' @examples
survprob <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "survprob")
  out <- list(estimator = metadata$estimator,
              horizon   = metadata$horizon,
              estimates = compute_survprob(metadata))
  class(out) <- "survprob"
  out
}
