
#' Create RCT Survival Metadata
#'
#' Create RCT survival metadata to be used for estimation of the restricted mean survival time and
#' survival probability.
#'
#' @param formula An object of class "formula". The left hand side should be specified using \code{Surv(time, status)}
#'   where time is the name of the variable containing follow-up time and status is the name of the indicator variable
#'   with 0 = right censored and 1 = event at \code{time}. The right hand side should contain the target variable of
#'   interest and baseline prognostic covariates.
#' @param target The name of the target variable of interest; i.e., the randomized condition.
#' @param data A data frame containing the variables in the model.
#' @param coarsen An optional integer that specifies if and how \code{time} should be categorized into coarser intervals.
#' @param estimator The method to be used for computing estimands. Options are "tmle" for Targeted Maximum Likelihood
#'   Estimation (the default), "aipw" for Augmented IPW, and "km" for Kaplan-Meier.
#' @param lrnrs_cens An optional \code{sl3} learner stack for estimation of the censoring model.
#'   Ignored if \code{estimator = "km"}. If \code{NULL} estimation will be performed using a saturated linear model instead.
#' @param lrnrs_hzrd An optional \code{sl3} learner stack for estimation of the outcome model.
#'   Ignored if \code{estimator = "km"}. If \code{NULL} estimation will be performed using a saturated linear model instead.
#'
#' @family survrct functions
#'
#' @return An R6 object of class "Survival".
#' @export
#'
#' @examples
#' if (requireNamespace("survival", quietly = TRUE)) {
#'   veteran <- survival::veteran
#'   veteran$trt <- veteran$trt - 1
#'   veteran$celltype <- factor(veteran$celltype)
#'   survrct(Surv(time, status) ~ trt + celltype + karno + diagtime + age + prior,
#'           target = "trt", data = veteran, coarsen = 7, estimator = "tmle")
#' }
survrct <- function(formula, target, data, coarsen = 1,
                    estimator = c("tmle", "aipw", "km"),
                    lrnrs_cens = NULL, lrnrs_hzrd = NULL) {
  Survival$
    new(formula, target, data, match.arg(estimator), lrnrs_cens, lrnrs_hzrd)$
    prepare_data(coarsen)$
    fit_nuis()
}

#' Estimate Restricted Mean Survival Time
#'
#' @param metadata An object of class "Survival" generated by a call to \code{metadata()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   RMST at all possible time horizons.
#'
#' @family survrct functions
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{rmst} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{horizon}{The time horizons RMST was evaluated at.}
#' \item{standard_error}{The computed estimates for each time horizon including the efficient influence function,
#'      standard errors, and confidence intervals.}
#'
#' @export
#'
#' @examples
#' if (requireNamespace("survival", quietly = TRUE)) {
#'   veteran <- survival::veteran
#'   veteran$trt <- veteran$trt - 1
#'   veteran$celltype <- factor(veteran$celltype)
#'   surv <- survrct(Surv(time, status) ~ trt + celltype + karno + diagtime + age + prior,
#'                   target = "trt", data = veteran, coarsen = 7, estimator = "tmle")
#'   rmst(surv, horizon = 50)
#' }
rmst <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "rmst")
  out <- list(estimator = metadata$estimator,
              horizon   = metadata$horizon,
              estimates = compute_rmst(metadata))
  class(out) <- "rmst"
  out
}

#' Estimate Survival Probabilities
#'
#' @param metadata An object of class "Survival" generated by a call to \code{metadata()}.
#' @param horizon The time horizon to evaluate at. If \code{NULL}, computes
#'   survival probabilities at all time points.
#'
#' @family survrct functions
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list of class \code{survprob} containing the following components:
#'
#' \item{estimator}{The estimation method used.}
#' \item{horizon}{The time horizons the survival probability was evaluated at.}
#' \item{standard_error}{The computed estimates for each time horizon including the efficient influence function,
#'      standard errors, and confidence intervals.}
#'
#' @export
#'
#' @examples
#' if (requireNamespace("survival", quietly = TRUE)) {
#'   veteran <- survival::veteran
#'   veteran$trt <- veteran$trt - 1
#'   veteran$celltype <- factor(veteran$celltype)
#'   surv <- survrct(Surv(time, status) ~ trt + celltype + karno + diagtime + age + prior,
#'                   target = "trt", data = veteran, coarsen = 7, estimator = "tmle")
#'   survprob(surv, horizon = 50)
#' }
survprob <- function(metadata, horizon = NULL) {
  metadata$evaluate_horizon(horizon, "survprob")
  out <- list(estimator = metadata$estimator,
              horizon   = metadata$horizon,
              estimates = compute_survprob(metadata))
  class(out) <- "survprob"
  out
}
