
nuisance <- function(self) {
  fit_H <- glm(self$formula_hzrd(), data = self$at_risk_evnt(), family = "binomial")
  fit_R <- glm(self$formula_cens(), data = self$at_risk_cens(), family = "binomial")
  fit_A <- glm(self$formula_trt(), data = self$at_risk_trt(), family = "binomial")

  list(
    hzrd_fit = fit_H,
    cens_fit = fit_R,
    trt_fit  = fit_A,
    hzrd_off = predict(fit_H, newdata = self$turn_off(), type = "response"),
    hzrd_on  = predict(fit_H, newdata = self$turn_on(), type = "response"),
    cens_off = predict(fit_R, newdata = self$turn_off(), type = "response"),
    cens_on  = predict(fit_R, newdata = self$turn_on(), type = "response"),
    trt_off  = 1 - predict(fit_A, newdata = self$turn_on(), type = "response"),
    trt_on   = predict(fit_A, newdata = self$turn_on(), type = "response")
  )
}

#' Return Nuisance Parameter Model Fits
#'
#' @param metadata An object of class "Survival" generated by a call to \code{metadata()}.
#'
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list containing the following components:
#'
#' \item{Hazard}{The fit for the outcome model.}
#' \item{Censoring}{The fit for the censoring model.}
#' \item{Treatment}{The fit for the treatment model.}
#'
#' @export
#'
#' @examples
#' if (requireNamespace("survival", quietly = TRUE)) {
#'   veteran <- survival::veteran
#'   veteran$trt <- veteran$trt - 1
#'   veteran$celltype <- factor(veteran$celltype)
#'   surv <- survrct(Surv(time, status) ~ trt + celltype + karno + diagtime + age + prior,
#'                   target = "trt", data = veteran, coarsen = 7, estimator = "tmle")
#'   get_fits(surv)
#' }
get_fits <- function(metadata) {
  list(Hazard = metadata$nuisance$hzrd_fit,
       Censoring = metadata$nuisance$cens_fit,
       Treatment = metadata$nuisance$trt_fit)
}
