nuisance <- function(self, lasso) {
  if (lasso) {
    return(fit_lasso(self))
  }

  fit_H <- glm(self$formula_hzrd(), data = self$at_risk_evnt(), family = "binomial")
  fit_R <- glm(self$formula_cens(), data = self$at_risk_cens(), family = "binomial")
  fit_A <- glm(self$formula_trt(), data = self$at_risk_trt(), family = "binomial")

  list(
    hzrd_fit = fit_H,
    cens_fit = fit_R,
    trt_fit = fit_A,
    hzrd_off = predict(fit_H, newdata = self$turn_off(), type = "response"),
    hzrd_on = predict(fit_H, newdata = self$turn_on(), type = "response"),
    cens_off = predict(fit_R, newdata = self$turn_off(), type = "response"),
    cens_on = predict(fit_R, newdata = self$turn_on(), type = "response"),
    trt_off = 1 - predict(fit_A, newdata = self$turn_on(), type = "response"),
    trt_on = predict(fit_A, newdata = self$turn_on(), type = "response")
  )
}

fit_lasso <- function(self) {
  on <- self$turn_on()
  off <- self$turn_off()

  H_m <- model.matrix(self$formula_hzrd(), self$at_risk_evnt())[, -1]
  R_m <- model.matrix(self$formula_cens(), self$at_risk_cens())[, -1]
  A_m <- model.matrix(self$formula_trt(), self$at_risk_trt())[, -1]

  H_mon <- model.matrix(self$formula_hzrd(), on)[, -1]
  H_moff <- model.matrix(self$formula_hzrd(), off)[, -1]

  R_mon <- model.matrix(self$formula_cens(), on)[, -1]
  R_moff <- model.matrix(self$formula_cens(), off)[, -1]

  A_o <- model.matrix(self$formula_trt(), self$surv_data)[, -1]

  pen <- rep(1, ncol(R_m))
  pen[grep("^as.factor\\(all_time\\)", colnames(R_m))] <- 0

  fit_H <- glmnet::cv.glmnet(H_m, as.matrix(self$at_risk_evnt()[["evnt"]]),
                             family = "binomial",
                             foldid = foldsids(nrow(H_m), self$at_risk_evnt()[["survrctId"]], 10))
  fit_R <- glmnet::cv.glmnet(R_m, self$at_risk_cens()[["cens"]],
                             family = "binomial", penalty.factor = pen,
                             foldid = foldsids(nrow(R_m), self$at_risk_cens()[["survrctId"]], 10))
  fit_A <- glmnet::cv.glmnet(A_m, self$at_risk_trt()[[self$trt]],
                             family = "binomial",
                             foldid = foldsids(nrow(A_m), self$at_risk_trt()[["survrctId"]], 10))

  list(
    hzrd_fit = fit_H,
    cens_fit = fit_R,
    trt_fit = fit_A,
    hzrd_off = bound01(as.vector(predict(fit_H, newx = H_moff, type = "response"))),
    hzrd_on = bound01(as.vector(predict(fit_H, newx = H_mon, type = "response"))),
    cens_off = bound01(as.vector(predict(fit_R, newx = R_moff, type = "response"))),
    cens_on = bound01(as.vector(predict(fit_R, newx = R_mon, type = "response"))),
    trt_off = bound01(as.vector(1 - predict(fit_A, newx = A_o, type = "response"))),
    trt_on = bound01(as.vector(predict(fit_A, newx = A_o, type = "response")))
  )
}

foldsids <- function(n, id, V) {
  out <- rep(0, n)
  folds <- origami::make_folds(n, cluster_ids = id, V = V)
  for (i in 1:length(folds)) {
    out[folds[[i]]$validation_set] <- i
  }
  out
}

#' Return Nuisance Parameter Model Fits
#'
#' @param metadata An object of class "Survival" generated by a call to \code{metadata()}.
#'
#' @seealso \code{\link{survrct}} for creating \code{metadata}.
#'
#' @return A list containing the following components:
#'
#' \item{Hazard}{The fit for the outcome model.}
#' \item{Censoring}{The fit for the censoring model.}
#' \item{Treatment}{The fit for the treatment model.}
#'
#' @export
#'
#' @examples
#' \donttest{
#' surv <- survrct(Surv(time, status) ~ trt + age + sex + obstruct +
#'                    perfor + adhere + surg,
#'                 target = "trt", data = colon, coarsen = 30, estimator = "tmle")
#' get_fits(surv)
#' }
get_fits <- function(metadata) {
  list(Hazard = metadata$nuisance$hzrd_fit,
       Censoring = metadata$nuisance$cens_fit,
       Treatment = metadata$nuisance$trt_fit)
}
